language: generic
sudo: required
services:
  - docker

before install:
  - docker build -t cgjonesdev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cgjonesdev/react-test npm test

after_success:
  - docker build -t cgjonesdev/multi-nginx ./nginx
  - docker build -t cgjonesdev/multi-client ./client
  - docker build -t cgjonesdev/multi-server ./server
  - docker build -t cgjonesdev/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cgjonesdev/multi-nginx
  - docker push cgjonesdev/multi-client
  - docker push cgjonesdev/multi-server
  - docker push cgjonesdev/multi-worker
